### ISSUE TITLE
Novel Prewriting

### ISSUE THREAD

**Issue by thebritican** [anovelmous-dev-squad/anovelmous#1]
A novel can currently only be crafted from dictionary words, not with custom proper names and places like a typical novel would have. There should be a means to save and query new names like **Tim** and **Jane** and new made up places like **Quixlberg**.

These options should also be made available whenever a noun is allowed via the grammar filter.

Creating these custom words will require user participation and the API needs to support their creation by users and voting on them in some manner to be added as possible terms for the novel.

Finally, descriptions should be allowed for these custom terms so users can reference who/what they are while writing the novel.

The more features that can eventually be added to prewriting can certainly help the anticipated novel achieve coherence.

**Comment by Jmmaroli** [comment]
Idea: If a proper noun such as "Tim" is voted as the next word, then it should be added to the entire token database.

**Comment by thebritican** [comment]
There is no free-form input allowed currently, since the Token resource is only allowed GETs.

The names should be established before the Novel is started, hence "Prewriting". This way, the user *will* see Tim and whatever other proper nouns were added as options.

I do not think proper nouns should be added to Token, simply because they are only relevant to Novels. Token should be a word or punctuation usable in any Novel, Chapter, etc.

This issue should contain a plan of action for implementing the concept of proper nouns and all they might entail. For instance, a few new resources like **Character**, **Place**, **PlotItem** .

Having these meaningful categories for a proper noun will make future UI views easy to implement when contributors need reminders about what places, characters, etc were established.

![image](https://cloud.githubusercontent.com/assets/3099999/9857063/63978fb6-5ae6-11e5-8174-8d7760749e01.png)

**Comment by thebritican** [comment]
### A quick update

In the front-end repo, a GraphQL implementation exists that should be portable to this python backend.

> This issue should contain a plan of action for implementing the concept of proper nouns and all they might entail. For instance, a few new resources like Character, Place, PlotItem.

The plan to actually map these GraphQL Objects to their ORM counterparts is TBD.

A branch currently exists for the GraphQL Implementation.
